### ISSUE TITLE
Please consider other license options

### ISSUE THREAD

**Issue by probonopd** [esiqveland/notify#10]
Hi @esiqveland, I would like to use notify in a MIT-licensed project. Do you allow this?

**Comment by esiqveland** [comment]
I would consider that, but I am not an expert on licensing. I noticed the dbus dependency is under a BSD license, maybe I need to use the same.

**Comment by probonopd** [comment]
Yes, a 3-clause or 2-clause BSD license would be much preferable over the current one and would be acceptable for me, too.

**Comment by esiqveland** [comment]
Made a release under BSD license.

**Comment by probonopd** [comment]
Thank you very much @esiqveland, this helps a lot.
