### ISSUE TITLE
Document how to use notification server's default ExpireTimeout

### ISSUE THREAD

**Issue by joonas-fi** [esiqveland/notify#12]
Change 2faf6e55739c4e48dab403481e90f2c8d94b01c3 is good in overall sense (Go-idiomatic to use `time.Duration` for time intervals).

I used to use this pattern:
```go
notify.Notification{
    ExpireTimeout: -1, // use default for notification daemon
}
```

Here's a quote from [the spec](https://specifications.freedesktop.org/notification-spec/notification-spec-latest.html#basic-design):

> If -1, the notification's expiration time is dependent on the notification server's settings, and may vary for the type of notification. If 0, never expire.

It is sent in the DBus protocol as milliseconds, so the duration has to be converted to milliseconds.

Now if I want to request the the notification server to dictate the expiration, I have to do this to get -1 sent over DBus:

```go
notify.Notification{
    ExpireTimeout: -1 * time.Millisecond, // use default for notification daemon
}
```

Which reads more confusing than the old unit-less -1 :smile:

But seeing this took some time for me to debug why my system's behaviour changed to weird, perhaps this could be documented somewhere?

Also would it make sense to expose `var ExpireTimeoutSetByNotificationServer = -1 * time.Millisecond ` from the package? Then we could do:

```go
notify.Notification{
    ExpireTimeout: notify.ExpireTimeoutSetByNotificationServer,
}
```

**Comment by esiqveland** [comment]
Thank you for reporting.

i will definitively include something like notify.ExpireTimeoutSetByNotificationServer

I find it a little odd though, like what would a zero value mean then? Feels like the zero value should be controlled by the server and -1 for no expiry. 😅


Now I wish I had defaulted to this value…

**Comment by esiqveland** [comment]
How about something like https://github.com/esiqveland/notify/pull/13 ?
