### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by lordofscripts** [esiqveland/notify#17]
I am trying to use this repository library in an experimental demo.

Despite having done the _go gets_ (for `notify` & `godbus/v5`) and have imported them, when I try to compile my demo _it complains that notify doesn't have_ `SoundWithName` nor `Variant`, and yet they are there in the source!

Strange thing that also when I issue go doc notify it shows all the types and constants except for `SoundWithName()` and `Variant{}`.

**Comment by esiqveland** [comment]
Can you try to do:

```
$ go get -u -v github.com/esiqveland/notify
$ go mod tidy
```
See if that helps?

**Comment by lordofscripts** [comment]
Will try if it happens again. I worked around it by redefining Variant in my code and using it without SoundWithName. Somehow all the other notify symbols were properly recognized.

**Comment by esiqveland** [comment]
Try with v0.12.0
