### ISSUE TITLE
Actions not shown on notification

### ISSUE THREAD

**Issue by lordofscripts** [esiqveland/notify#18]
In my experiment I do the same as your test:

- create a `Notification` without `Action`
-  send it
- clicked on it to close it

Then I use the same `Notification` and add  the two `Action` objects to `Notification.Actions` and send it again to the server.

In both cases the notification pops up and if not _clicked_ **(Close)** it eventually times out. However, the Action doesn't seem to work:

- The **open/cancel** actions injected into the `Notification` object do not appear visually on the notification body.
- When one clicks on any part of the body, the action-enabled notification does nothing else than closing. So the `onAction` callback never gets invoked.

So:
-  Notification body may be pretended with (A) but that can be disabled in the server.
- the actions are apparently not rendered in the body. When user does **Middle mouse click** the _system is supposed to display a context menu but it doesn't_.

**Comment by lordofscripts** [comment]
I noticed the notification body is pretended with the following:

- (A) it has a tion(s)
- (U) it has an URL

Also learned that with `Dunst` you interact with them through:

- Left mouse: close notification
- Middle mouse: URL or action activation

When it is an URL it launches the browser. However, for Actions it is supposed (as per `Dunst` config file) to invoke /use/bin/dmenu but it wasn't installed in my system, it is part of `shitless-tools` or something like that. I installed it but even with that the actions are not rendered nor activated.

So, still in progress...

**Comment by esiqveland** [comment]
Sounds like this is up to the notification server to decide?

The actions work as expected on XFCE and Gnome 46:

The spec separates Closing signal from the Action signals. If the notification is only Closed, default closed action or closed by user, the Closed signal is sent. Action signal is _only_ sent when the action specifically is clicked by the user.

Except for gnome 38-44 the Action invoked signal was actually duplicated and sent twice by the notification server...

**Comment by lordofscripts** [comment]
Apparently yes. I guess full Gnome has a notification dashboard that isn't available on Raspberry (Debian with stripped down KDE/Gnome).

I saw that in the dunst notification server you can configure the mouse actions. In particular I noticed that:
-  the middle mouse (in mine) is used for interacting with Actions, and
- that middle mouse is configured to firs do the action and then do the closing.

So there is a lot that can be configured in the server. And since (A) appears prepended when the notification has actions, it means the server is aware of it. Therefore, it isn't an issue of this package. But good to know for anybody new to implementing notifications.
