### ISSUE TITLE
Color-code Urgency

### ISSUE THREAD

**Issue by lordofscripts** [esiqveland/notify#20]
I was originally using [TheCreeper/go-notify](https://github.com/TheCreeper/go-notify/blob/master/dbus.go) but switched to your excellent package because the other only supported sending without signals.

The other package uses DBus Hints to set up the `Notification` _urgency_. It is set the same as you use sound hints here.

So, I used the same to specify the urgency using your package. However, I noticed that with his, the pop ups have different background colors based on the "`urgency`" hint, but when I do it with yours they all have the same color. His code doesn't set colors anywhere so it is done by the **DBus server**, so I guess that your package (or perhaps it's underlying dbus/V5 is annihilating this hint.

Any ideas?

**Comment by lordofscripts** [comment]
I found out the color coding is part of the server configuration, `Dunst` in my case. And it is properly configured.

However, I am still puzzled why with the same notification server `(Dunst)`, the other library works well with coloring notification and this one doesn't. The difference being that the other doesn't depend on others for communication with the server, and this one depends on `godbus/dbus/v5`.

**Comment by esiqveland** [comment]
Can you post a self contained sample where you use the Urgency hint?

**Comment by esiqveland** [comment]
I tested a bit on Gnome 46.

Seems like exact behavior is up to the notification server.

UrgencyLow (the default?) actually skips sound on Gnome 46.
When I set Normal or Critical, the sound plays.
For Normal, the action buttons are only visible inside notification center, not on the notification.
On Critical, action buttons are visible both on notification and on the notification card inside notification center.

**Comment by lordofscripts** [comment]
I am on a Raspberry Pi, although it has a few Gnome packages, it uses a lightweight window manager. In my system the notifications appear on the top right but there is no notification center of no notification area I could see.
 
When it is Urgent a (U) is prepended to the body, but low & normal look the same.

For setting **Urgency**, it uses the same form for setting `sound-name`, `sound-file` and `category`.

```
 
const (
  urgencyLow = byte(0)
  urgencyNormal = byte(1)
  urgencyCritical = byte(2)
)

func SetHighPriority(n *Notification) { 
  varU := &Variant{"urgency", dbus.MakeVariant(urgency critical)
  n.Hints[varU.ID] = varU.Variant
}


```

**Comment by esiqveland** [comment]
I added Urgency to v0.12.0:

```
func (n *Notification) SetUrgency(urgency Urgency) {
	n.AddHint(HintUrgency(urgency))
}
```
