### ISSUE TITLE
Default Action

### ISSUE THREAD

**Issue by lordofscripts** [esiqveland/notify#24]
When you set more than one `Action` in a `Notification` you can (and should!) mark one as the default action. Currently your package doesn't handle that use case, yet it is very easy to do (just found out!).

See [How to set default action](https://github.com/dunst-project/dunst/discussions/1360)

So basically, the action _name_ should be `default` but the _label_ can be anything.

**Comment by esiqveland** [comment]
Shouldn't that be same as a `Action{Key: "default", Label: "My default action"}` ?

**Comment by lordofscripts** [comment]
Yes, but the documentation doesn't mention it anywhere. I spent quite a lot of time browsing DBus & Dunst code. I added it in my wrapper, as all that time would have been better spent.

**Comment by esiqveland** [comment]
Is this part of the Freedesktop specification? I could perhaps provide a way to make it more obvious.

**Comment by esiqveland** [comment]
Yes, i found it and pushed a helper in https://github.com/esiqveland/notify/commit/6f7ebc583bbc475fc073ff036872a81db8ea3077
