### ISSUE TITLE
Multiple notifications get mixed up

### ISSUE THREAD

**Issue by probonopd** [esiqveland/notify#8]
Thanks for this useful library. When I open multiple notifications with actions, it seems that when the user triggers an action (by pressing a button) in one of the notifications, the action gets executed as often as there are notifications, and the buttons in the other notifications no longer work.

Code:

https://github.com/probonopd/go-appimage/blob/f1f729f5e55d6f58b7f988dd522699df7f475090/src/appimaged/notification.go#L104

Am I doing it wrong?

**Comment by esiqveland** [comment]
Hi, thank you for reporting and good description.

This might be a bug in the library. It might also be related to this notifier.Close() call you deferred here: https://github.com/probonopd/go-appimage/blob/f1f729f5e55d6f58b7f988dd522699df7f475090/src/appimaged/notification.go#L83

I am on mobile now so I cant do much further checking now.

**Comment by esiqveland** [comment]
Yes, I think it stops because your method exits and calls .Close after the first signal is delivered.

I also should leave closing the underlying dbus.Conn to the caller, which owns the connection: https://github.com/esiqveland/notify/blob/master/notification.go#L346

DBus is a bus so when one notification is dismissed, all the notifier objects you created sees a copy of the same ClosedNotification action

**Comment by probonopd** [comment]
Thanks @esiqveland. Sorry if I am asking stupid questions, as I am new to both Go and DBus.

My application wants to put up a message saying that an application can be updated whenever it encounters an application for which a newer version exists.

I was thinking that I should launch a go routine whenever this happens ([here](https://github.com/probonopd/go-appimage/blob/f1f729f5e55d6f58b7f988dd522699df7f475090/src/appimaged/mqtt.go#L138)), and let the go routine have a notification brought up on the screen ([here](https://github.com/probonopd/go-appimage/blob/f1f729f5e55d6f58b7f988dd522699df7f475090/src/appimaged/notification.go#L20)), and also act upon any buttons the user might click in this notification ([here](https://github.com/probonopd/go-appimage/blob/f1f729f5e55d6f58b7f988dd522699df7f475090/src/appimaged/notification.go#L97-L99)).

I was blindly assuming that when I send the notification, then the [go channel](https://github.com/probonopd/go-appimage/blob/f1f729f5e55d6f58b7f988dd522699df7f475090/src/appimaged/notification.go#L94) would get messages only for the _corresponding_ notification ID rather than for any other notification. Apparently this assumption is wrong.

How would you tackle this task? How does one bring up multiple notifications during the lifetime of a long-running process, and then react correctly to buttons pressed by the user in those notifications?

**Comment by esiqveland** [comment]
You will need to save the `ID` you get back from `SendNotification`, then listen for signals on this `ID`.

Usually you would create a single `Notifier` instance for your application, then keep this instance alive and re-use it. To receive the signals from dbus, it needs to do some setup, such as register as a service in dbus. This is why the component should be re-used between invocations and why a struct is needed to deliver signals.

I started a [redesign ](https://github.com/esiqveland/notify/pull/9) using callback functions that hopefully will make this functionality a bit clearer.

**Comment by probonopd** [comment]
Thank you very much. I'd highly appreciate an example to go along with your redesign.

**Comment by esiqveland** [comment]
I feel that will complicate the example and take away from first use of it, so I prefer not to include such details there, but it would be something like this:

```
	var memory = map[uint32]*notify.Notification{}
	id, err := notifier.SendNotification(n)
	if err != nil {
		log.Printf("error sending notification: %v", err)
	} else {
		memory[id] = &n
		log.Printf("sent notification id: %v", id)
	}
```

Then you can use `memory` to lookup the `Action.ID` when one comes back and check if this is a notification you produced earlier.

**Comment by probonopd** [comment]
Thank you very much @esiqveland. This helps me a tremendous lot.
